spring.application.name=Springboot-API-REST
server.port=8081
spring.web.allow-cors=true

# =============================================================
# Configuración de la base de datos MySQL en AWS
# =============================================================
spring.datasource.url=jdbc:mysql://${DB_ENDPOINT}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExists=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.platform=mysql

# =============================================================
# Tolerancia a la espera de la base de datos (Evita CrashLoop en ECS)
# =============================================================
# Indica a Spring Boot que espere hasta 40 segundos a que el puerto 3306 esté listo
spring.datasource.hikari.connection-timeout=40000
spring.datasource.hikari.maximum-pool-size=5

# =============================================================
# Configuración de Hibernate
# =============================================================
spring.jpa.database=mysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# =============================================================
# Documentación Swagger
# =============================================================
springdoc.swagger-ui.path=/swagger-ui.html
